source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import SignUp, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', SignUp.as_view(), name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter


router = DefaultRouter()


app_name = 'api'

urlpatterns = [
    path('', include(router.urls))
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic import DeleteView

from webapp.views import IndexView, FileCreate, FileUpdate, DetailFile, FileDelete

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('file/create/', FileCreate.as_view(), name='create_file'),
    path('file/update/<int:pk>/', FileUpdate.as_view(), name='update_file'),
    path('file/<int:pk>/', DetailFile.as_view(), name='file_detail'),
    path('file/delete/<int:pk>/', FileDelete.as_view(), name='file_delete')
]

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models

from django.db import models

ACCESS_CHOICES = (
    ('common', 'Обычный'),
    ('hidden', 'Скрытый'),
    ('private', 'Приватный'),
)


class File(models.Model):
    file = models.FileField(upload_to='user_file', verbose_name='Файл')
    name = models.CharField(max_length=50, verbose_name='Подпись к файлу')
    author = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='author_file', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    general_access = models.CharField(max_length=50, choices=ACCESS_CHOICES, default=ACCESS_CHOICES[0][0],
                                      verbose_name='Общий доступ')
    users_private = models.ManyToManyField('auth.User', related_name='file_private', verbose_name='Приват')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('Email has already registered', code='email_registered')
        except User.DoesNotExist:
            return email

source/webapp/forms.py
from django import forms

from webapp.models import File


class SearchForm(forms.Form):
    search = forms.CharField(max_length=40, label='Form', required=False)


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at', 'author', 'users_private']


class FileFormForCommon(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at', 'author', 'users_private', 'general_access']

source/accounts/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from accounts.forms import SignUpForm


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'user_create.html'
    success_url = reverse_lazy('accounts:login')


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        files = context['user_obj'].author_file.order_by('-creation_date')
        self.paginate_files_to_context(files, context)
        return context

    def paginate_files_to_context(self, files, context):
        paginator = Paginator(files, 2, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['files'] = page.object_list
        context['is_paginated'] = page.has_other_pages()

source/api/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from webapp.forms import SearchForm, FileForm, FileFormForCommon
from webapp.models import File


class IndexView(ListView):
    model = File
    template_name = 'index.html'
    paginate_by = 10
    paginate_orphans = 1
    ordering = '-created_at'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.filter(general_access='common')

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class FileCreate(CreateView):
    model = File
    template_name = 'create_file.html'
    # form_class = FileForm

    def get_success_url(self):
        return reverse('webapp:index')

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return FileForm
        else:
            return FileFormForCommon

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.request.user.is_authenticated:
            self.object.author = self.request.user
            self.object.save()
        else:
            self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class FileUpdate(UserPassesTestMixin, UpdateView):
    form_class = FileForm
    template_name = 'update_file.html'
    model = File
    context_object_name = 'file'

    def test_func(self):
        file = File.objects.filter(author__username=self.request.user, pk=self.kwargs['pk'])
        if file or self.request.user.has_perm('webapp.change_file'):
            return True

    def get_success_url(self):
        return reverse('webapp:file_detail', kwargs={'pk': self.object.pk})


class DetailFile(UserPassesTestMixin, DetailView):
    pk_url_kwarg = 'pk'
    model = File
    template_name = 'file.html'
    context_object_name = 'file'

    def test_func(self):
        file = self.get_object()
        user = self.request.user
        if (file.general_access == 'private' and user in file.users_private.all()) or file.author == user or\
                file.general_access == 'common':
            return True


class FileDelete(UserPassesTestMixin, DeleteView):
    model = File
    context_object_name = 'file'
    template_name = 'delete_file.html'
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        file = File.objects.filter(author__username=self.request.user, pk=self.kwargs['pk'])
        if file or self.request.user.has_perm('webapp.delete_file'):
            return True

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
        <h1 class="text-center">Регистрация</h1>
        <form action="{% url 'accounts:register' %}" method="post">
            {% include "partial/form.html" %}
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if user.pk == user_obj.pk %}
{#        <li class="nav-item"><a class="nav-link" href="{% url "accounts:update" user_obj.pk %}">Редактировать</a></li>#}
{#        <li class="nav-item"><a class="nav-link" href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>#}
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Личный кабинет</h1>
    <div class="row">
        <div class="col col-12 col-sm-10 col-md-8 col-lg-6 m-auto">
            {% if user_obj.profile.avatar %}
                <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid" alt="{{ user_obj.username }}">
            {% endif %}
            <div class="mt-3">
                <p><b>Имя пользователя:</b> {{ user_obj.username }}</p>
                <p><b>Имя:</b> {{ user_obj.first_name }}</p>
                <p><b>Фамилия:</b> {{ user_obj.last_name }}</p>
            </div>
        </div>
    </div>
    <h2 class="text-center">Загруженные файлы:</h2>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="row">
        {% for file in user_obj.author_file.all %}
            {% if file.general_access == 'common' or file.author == request.user %}
                <div class="col col-12 col-md-6 col-lg-4 col-xl-3">
                    {% include "partial/file_card.html"%}
                </div>
            {% endif %}
        {% endfor %}
</div>
{% endblock %}

source/webapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block style_links %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
            {% block menu %}{% endblock %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'accounts:detail' request.user.pk %}" class="nav-link">
                    Привет, {{ request.user.username }}!
                </a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link">Регистрация</a></li>
                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container mt-3">
    {% block content %}{% endblock %}
</div>
<script src={% static "/js/jquery-3.4.1.min.js"%}></script>
<script src={% static "/js/popper.min.js"%}></script>
<script src={% static "/js/bootstrap.min.js"%}></script>
{% block script %}{% endblock %}
</body>
</html>

source/webapp/templates/create_file.html
{% extends 'base.html' %}
{% block title %}Добавить файл{% endblock %}
{% block content %}
    <h1 class="text-center">Добавить файл</h1>
    <form action="{% url "webapp:create_file" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Добавить" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/delete_file.html
{% extends 'base.html' %}
{% block title %}Удалить Файл{% endblock %}
{% block content %}
    <h1>Вы уверены, что вы хотите удалить файл: {{ file.name }} ?</h1>
    <form method="POST" action="{% url 'webapp:file_delete' file.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Да" id="input" class=" btn btn-danger"></p>
        <p><a href="{% url 'webapp:index'%}" class="btn btn-primary">Отмена</a></p>
    </form>
{% endblock %}

source/webapp/templates/file.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{file.name}}{% endblock %}
{% block menu %}
    {% if perms.webapp.change_file or file.author == request.user %}
        <li class="nav-item"><a href="{% url 'webapp:update_file' file.pk %}" class="nav-link">Редактировать</a></li>
        <li class="nav-item"><a href="{% url 'webapp:file_delete' file.pk %}" class="nav-link">Удалить</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>{{ file.name }}</h1>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Подпись:{{ file.name }}</h5>
        <p class="card-text">Автор: <a href="{% if file.author.pk %}{% url 'accounts:detail' file.author.pk %}{% endif %}">{{ file.author|default_if_none:"Аноним"}}</a></p>
        <p class="card-text">Дата создания: {{ file.created_at }}</p>
        <p><a href="{{ file.file.url }}" download=""
              class="btn btn-primary">Скачать</a></p>
    </div>
</div>


{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Файлы{% endblock %}
{% block menu %}
    <li class="nav-item"><a href="{% url 'webapp:create_file' %}" class="nav-link">Загрузить файл</a></li>
{% endblock %}
{% block content %}
    {% include 'partial/search.html' %}
    <h1 class="text-center">Файлы</h1>
    <div class="row">
        {% for file in file_list %}
            <div class="col col-3">
                {% include 'partial/file_card.html' %}
            </div>
        {% endfor %}
    </div>
    {% include 'partial/pagination.html' %}
{% endblock %}

source/webapp/templates/partial/file_card.html
<div class="card mb-2">
    <div class="card-body">
        <h5 class="card-title"><a href="{% url 'webapp:file_detail' file.pk %}">{{ file.name }}</a></h5>
        <p class="card-text"><a href="{% if file.author.pk %}{% url 'accounts:detail' file.author.pk %}{% endif %}">{{ file.author|default_if_none:"Аноним"}}</a></p>
        <p class="card-text">{{ file.created_at }}</p>
        <p><a href="{{ file.file.url }}" download=""
              class="btn btn-primary">Скачать</a></p>
    </div>
</div>

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="mr-3">{{ field.label }}</label>
        {% if field|field_type == 'imagefield' or field|field_type == 'filefield' %}
            {{ field }}
        {% else %}
            {{ field|add_class:"form-control" }}
        {% endif %}
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

source/webapp/templates/partial/pagination.html
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}{% endif %}&page=1">&laquo; В начало</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}{% endif %}&page={{ page_obj.previous_page_number }}">Назад</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Назад</span>
            </li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
                <li class="page-item active" aria-current="page">
                     <span class="page-link">{{ page_obj.number }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}{{ query }}{% endif %}&page={{ page }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}{% endif %}&page={{ page_obj.next_page_number }}">Далее</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Далее</span>
            </li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}{% endif %}&page={{ paginator.num_pages }}">В конец &raquo;</a></li>
    </ul>
</nav>

source/webapp/templates/partial/search.html
<form class="text-center" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Search">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>

source/webapp/templates/partial/update_form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
    <p>{{ field }}</p>
{% endfor %}

<p><input type="submit" value="{{ button_text }}"></p>

source/webapp/templates/update_file.html
{% extends 'base.html' %}
{% block title %}{{ file.name }}{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Редактирование файла</h1>
    <form action="{% url 'webapp:update_file' file.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/update_form.html' with button_text='Обновить' %}
    </form>
{% endblock %}